language: python
sudo: false
python:
  - "2.7"
install:
  - pip install -r requirements-test.txt
before_script:
  - flake8 uwhoisd tests tools setup.py
script:
  - py.test --doctest-modules uwhoisd tests
