language: python
cache: pip
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  # Hack to work around brokenness in the pyev package.
  - pip install .
script:
  - nosetests
