language: python
sudo: false
python:
  - "2.6"
  - "2.7"
install:
  - pip install flake8
  # Hack to work around brokenness in the pyev package.
  - pip install .
before_script:
  - flake8 uwhoisd tests
script:
  - py.test --doctest-modules uwhoisd tests
